#!/usr/bin/env python3
"""Generates app/src/main/assets/words_en.txt, the swipe decoder's
frequency-ordered dictionary (`word<TAB>rank` lines, lower rank = more
frequent — the decoder's frequency bonus is a function of rank/maxRank).

Source: wordfreq v3 (https://github.com/rspeer/wordfreq) top-60000 English
list — a ~2021 multi-corpus snapshot (Wikipedia, OpenSubtitles 2018,
SUBTLEX, Google Books Ngrams, OSCAR web, Twitter, Reddit), so it covers
modern tech terms, brands, names and slang that the old google-10000
(2006 web n-grams) list lacked. Data license: CC BY-SA 4.0 — see the
NOTICE file in the repository root; keep the attribution header in the
generated file intact.

Pipeline:
  1. top_n_list('en', 60000), filtered to ^[a-z]{2,}$ (the decoder only
     has a-z keys; 2-letter words are kept because it admits them on very
     short trails, single letters/digits/contractions are useless).
  2. Vowel-less tokens of 3+ letters are dropped ("pwr", "thx", "njpw",
     "msg"-class Twitter/texting abbreviations): they otherwise become
     short-subsequence candidates that beat the intended word on swipe
     trails (empirically, "pwr" out-scored "power" on the p-o-w-e-r
     trail). Words with 'y' as their vowel stay ("sky", "gym", "rhythm").
     Known collateral: typed initialisms go too ("html", "pdf", "php",
     "xml", "rss", "dvd", "nfl") — accepted, they are tapped, not swiped;
     any the user wants back belong in SUPPLEMENT below.
  3. The previous word list's words that are NOT in this filtered list
     (legacy 2006-web junk like "phentermine" or "bizjournalshire") are
     DROPPED — reported on stdout and optionally written to a review file.
  4. The manual SUPPLEMENT below (keyboard-era vocabulary) merges at each
     word's wordfreq rank; supplement words unknown to wordfreq append at
     the tail (lowest frequency), same convention as before.

Requires the `wordfreq` pip package. Install it in a venv, never globally:

    python3 -m venv .venv-wordfreq
    .venv-wordfreq/bin/pip install wordfreq
    .venv-wordfreq/bin/python tools/generate_words_en.py [dropped_words.txt]

Run manually from the repo root, never from Gradle.
"""

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_FILE = REPO_ROOT / "app/src/main/assets/words_en.txt"

TOP_N = 60000

# The decoder's candidate universe is the QWERTY letter keys; anything else
# (digits, apostrophes, unicode) can never be scored and only bloats the
# asset. 2-letter words stay: the decoder admits them on trails <= 3.5 key
# widths ("hi", "up").
WORD_OK = re.compile(r"^[a-z]{2,}$")

# Vowel-less tokens of 3+ letters ("pwr", "thx", "njpw", "msg") are texting
# abbreviations, not swipe targets — and worse, as short consonant
# subsequences of real words' key paths they hijack swipes ("pwr" beat
# "power" on the p-o-w-e-r trail in SwipeDecoderTest). 'y' counts as a
# vowel here so "sky", "gym", "spy", "rhythm" survive.
VOWEL_LESS = re.compile(r"^[bcdfghjklmnpqrstvwxz]{3,}$")

# Hand-maintained supplement: words a keyboard user expects regardless of
# corpus frequency. Words present in the wordfreq list keep their wordfreq
# rank; the rest append at the tail.
SUPPLEMENT = [
    "swipe",
    "swipes",
    "swiped",
    "swiping",
    "emoji",
    "emojis",
    "texting",
    "texter",
    "autocomplete",
    "autocorrect",
    "touchscreen",
    "gestures",
]

HEADER = [
    "# English swipe dictionary, generated by tools/generate_words_en.py.",
    "# Source: wordfreq v3 (https://github.com/rspeer/wordfreq) by Robyn",
    "# Speer — multi-corpus word frequencies (~2021 snapshot: Wikipedia,",
    "# OpenSubtitles 2018, SUBTLEX, Google Books Ngrams, OSCAR, Twitter,",
    "# Reddit). Data license: CC BY-SA 4.0",
    "# (https://creativecommons.org/licenses/by-sa/4.0/) — full attribution",
    "# in the NOTICE file at the repository root.",
    "# Format: word<TAB>rank, lower rank = more frequent. Dictionary.load",
    "# skips lines without this shape (like these comments).",
    "# A manual supplement (keyboard vocabulary like \"swipe\") is merged",
    "# by the generator's SUPPLEMENT list — edit there and regenerate.",
]


def load_current_words(path: Path) -> list[str]:
    """Words of the existing list, in file order. Same lenient parsing as
    Dictionary.load: a line needs a tab and an integer rank to count."""
    words = []
    for line in path.read_text(encoding="utf-8").splitlines():
        tab = line.find("\t")
        if tab <= 0:
            continue
        try:
            int(line[tab + 1:])
        except ValueError:
            continue
        words.append(line[:tab])
    return words


def main() -> None:
    try:
        from wordfreq import top_n_list
    except ImportError:
        sys.exit(
            "wordfreq is not installed. Create a venv and install it there:\n"
            "  python3 -m venv .venv-wordfreq\n"
            "  .venv-wordfreq/bin/pip install wordfreq\n"
            "  .venv-wordfreq/bin/python tools/generate_words_en.py"
        )

    words = [w for w in top_n_list("en", TOP_N)
             if WORD_OK.fullmatch(w) and not VOWEL_LESS.fullmatch(w)]
    word_set = set(words)

    # Supplement: merge at wordfreq rank when known, append at the tail
    # (lowest frequency) otherwise.
    tail = [w for w in SUPPLEMENT if w not in word_set]
    words.extend(tail)
    final_set = word_set | set(tail)

    # Report which words of the previous list did not survive — these are
    # the legacy-only words being dropped (2006-web junk for the most
    # part); review before committing a regenerated list.
    dropped = [w for w in load_current_words(OUT_FILE) if w not in final_set]

    lines = HEADER + [f"{word}\t{rank}" for rank, word in enumerate(words, start=1)]
    OUT_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")

    if len(sys.argv) > 1:
        Path(sys.argv[1]).write_text("\n".join(dropped) + "\n", encoding="utf-8")

    size = OUT_FILE.stat().st_size
    print(f"wrote {OUT_FILE}")
    print(f"  words:         {len(words)} ({len(word_set)} from wordfreq top-{TOP_N}, "
          f"{len(tail)} supplement-only at tail)")
    print(f"  dropped:       {len(dropped)} words from the previous list"
          + (f" (listed in {sys.argv[1]})" if len(sys.argv) > 1 else
             " (pass an output path to list them)"))
    print(f"  file size:     {size} bytes ({size / 1024:.0f} KiB)")


if __name__ == "__main__":
    main()
